### ISSUE TITLE
後期中間-6 ブランチで 不明 > ... > 不明 を押すと TypeError: can't access property "", a is undefined

### ISSUE THREAD

**Issue by satackey** [ohyama4z/Kakomon-Management-System#111]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/ohyama4z/Kakomon-Management-System/issues/111)

![image](https://user-images.githubusercontent.com/21271711/99895770-4dcb0280-2ccd-11eb-8e7d-aaa8b5becd21.png)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars2.githubusercontent.com/u/21271711?v=4' alt='satackey' width=24 height=24> satackey](https://issuehunt.io/u/satackey) ($5.00)

### Submitted pull Requests
- [#112 不明を参照するのを忘れてた](https://issuehunt.io/r/ohyama4z/Kakomon-Management-System/pull/112)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/ohyama4z/Kakomon-Management-System/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by satackey** [comment]
@ohyama4z

**Comment by ohyama4z** [comment]
データツリーの構造上プロパティ名に`'不明'`を参照しなきゃいけないけど、
実際にクリックしたアイテムに格納されている`period`とかのデータは空文字列なので、こうなった感じでした

**Comment by satackey** [comment]
:naruhodo:

**Comment by ohyama4z** [comment]
PR立てたので流し見してapproveしてくれるとうれしい(admin mergeは心が痛むので)
